/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { ICodeStyleProfile, IndentStyle, LineEnding } from '../common/codeStyleTypes.js';

// ---------------------------------------------------------------------------
// Import
// ---------------------------------------------------------------------------

/**
 * Parses the text of an `.editorconfig` file and returns the settings from
 * the `[*]` section mapped to a partial {@link ICodeStyleProfile}.
 */
export function parseEditorConfig(content: string): Partial<ICodeStyleProfile> {
	const result: Partial<ICodeStyleProfile> = {};
	let inGlobalSection = false;
	let indentStyle: IndentStyle | undefined;
	let indentSize: number | undefined;

	for (const rawLine of content.split(/\r?\n/)) {
		const line = rawLine.trim();
		if (!line || line.startsWith('#') || line.startsWith(';')) {
			continue;
		}

		const sectionMatch = /^\[(.+)\]$/.exec(line);
		if (sectionMatch) {
			inGlobalSection = sectionMatch[1] === '*';
			continue;
		}

		if (!inGlobalSection) {
			continue;
		}

		const eqIdx = line.indexOf('=');
		if (eqIdx === -1) {
			continue;
		}

		const key = line.slice(0, eqIdx).trim().toLowerCase();
		const value = line.slice(eqIdx + 1).trim().toLowerCase();

		switch (key) {
			case 'indent_style':
				indentStyle = value === 'space' ? 'spaces' : 'tabs';
				break;
			case 'indent_size':
			case 'tab_width': {
				const n = parseInt(value, 10);
				if (!isNaN(n)) { indentSize = n; }
				break;
			}
			case 'end_of_line':
				if (value === 'lf' || value === 'crlf' || value === 'cr') {
					result.lineEnding = value as LineEnding;
				}
				break;
			case 'trim_trailing_whitespace':
				result.trimTrailingWhitespace = value === 'true';
				break;
			case 'insert_final_newline':
				result.insertFinalNewline = value === 'true';
				break;
			case 'max_line_length':
				result.maxLineLength = value === 'off' ? 0 : (parseInt(value, 10) || 0);
				break;
		}
	}

	if (indentStyle !== undefined || indentSize !== undefined) {
		result.indent = {
			style: indentStyle ?? 'tabs',
			size: indentSize ?? 4,
		};
	}

	return result;
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/**
 * Generates `.editorconfig` file content from an {@link ICodeStyleProfile}.
 */
export function generateEditorConfig(profile: ICodeStyleProfile): string {
	const lines: string[] = [
		'# Generated by Cobblestone Editor \u2014 Code Style Manager',
		'root = true',
		'',
		'[*]',
		`indent_style = ${profile.indent.style === 'spaces' ? 'space' : 'tab'}`,
		`indent_size = ${profile.indent.size}`,
	];

	if (profile.lineEnding !== 'auto') {
		lines.push(`end_of_line = ${profile.lineEnding}`);
	}

	lines.push(`trim_trailing_whitespace = ${profile.trimTrailingWhitespace}`);
	lines.push(`insert_final_newline = ${profile.insertFinalNewline}`);

	if (profile.maxLineLength > 0) {
		lines.push(`max_line_length = ${profile.maxLineLength}`);
	}

	return lines.join('\n') + '\n';
}
