/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { ICodeStylePreset } from '../common/codeStyle.js';
import { ICodeStyleProfile } from '../common/codeStyleTypes.js';

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

function preset(name: string, description: string, profile: ICodeStyleProfile): ICodeStylePreset {
	return { name, description, builtIn: true as const, profile };
}

// ---------------------------------------------------------------------------
// Preset definitions
// ---------------------------------------------------------------------------

/**
 * All built-in presets shipped with the editor.
 * They are never stored in configuration — they are always derived from code.
 */
export const BUILT_IN_PRESETS: readonly ICodeStylePreset[] = [

	// ---- Relaxed (no enforcement) ----------------------------------------

	preset(
		'Relaxed',
		'No style enforcement. All checks are disabled. A good starting point for exploration.',
		{
			lineEnding: 'auto',
			insertFinalNewline: false,
			trimTrailingWhitespace: false,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'hint',
			indent: { style: 'tabs', size: 4 },
			quotes: { '*': 'any' },
			semicolons: { '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { '*': 'any' },
			namingRules: [],
		},
	),

	// ---- Prettier -------------------------------------------------------

	preset(
		'Prettier',
		'Matches Prettier\'s default configuration: 2-space indent, double quotes, no semicolons, ES5 trailing commas, 80-char line limit.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 80,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 2 },
			quotes: {
				'*': 'double',
				'html': 'double',
			},
			semicolons: { '*': 'never' },
			trailingCommas: { '*': 'es5' },
			braceStyle: { '*': 'same-line' },
			namingRules: [],
		},
	),

	// ---- Airbnb ----------------------------------------------------------

	preset(
		'Airbnb',
		'Based on the Airbnb JavaScript Style Guide: 2-space indent, single quotes, always semicolons, trailing commas, camelCase variables/functions, PascalCase classes.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 100,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 2 },
			quotes: {
				'*': 'single',
				'jsx': 'double',
				'javascriptreact': 'double',
				'typescriptreact': 'double',
			},
			semicolons: { '*': 'always' },
			trailingCommas: { '*': 'always' },
			braceStyle: { '*': 'same-line' },
			namingRules: [
				{
					id: 'airbnb-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'airbnb-fn-camel',
					kind: 'function',
					style: 'camelCase',
					languages: ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'airbnb-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- Google ----------------------------------------------------------

	preset(
		'Google',
		'Based on the Google JavaScript/TypeScript Style Guide: 2-space indent, single quotes, always semicolons, 80-char line limit, camelCase identifiers, PascalCase classes, SCREAMING_SNAKE_CASE constants.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 80,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 2 },
			quotes: { '*': 'single' },
			semicolons: { '*': 'always' },
			trailingCommas: { '*': 'always' },
			braceStyle: { '*': 'same-line' },
			namingRules: [
				{
					id: 'google-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['javascript', 'typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'google-fn-camel',
					kind: 'function',
					style: 'camelCase',
					languages: ['javascript', 'typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'google-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['javascript', 'typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'google-const-screaming',
					kind: 'constant',
					style: 'SCREAMING_SNAKE_CASE',
					languages: ['javascript', 'typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'google-iface-pascal',
					kind: 'interface',
					style: 'PascalCase',
					languages: ['typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- StandardJS ------------------------------------------------------

	preset(
		'Standard JS',
		'Follows the StandardJS style: 2-space indent, single quotes, NO semicolons, always trailing commas, LF line endings.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 2 },
			quotes: { '*': 'single' },
			semicolons: { '*': 'never' },
			trailingCommas: { '*': 'never' },
			braceStyle: { '*': 'same-line' },
			namingRules: [],
		},
	),

	// ---- Microsoft / VS Code style --------------------------------------

	preset(
		'Microsoft (VS Code)',
		'The style used by the VS Code / Cobblestone Editor source: hard tabs, 4-wide, single quotes, always semicolons, PascalCase classes/interfaces (I-prefix), camelCase variables/functions.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'tabs', size: 4 },
			quotes: { '*': 'single' },
			semicolons: { '*': 'always' },
			trailingCommas: { '*': 'any' },
			braceStyle: { '*': 'same-line' },
			namingRules: [
				{
					id: 'ms-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['typescript', 'javascript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'hint',
				},
				{
					id: 'ms-fn-camel',
					kind: 'function',
					style: 'camelCase',
					languages: ['typescript', 'javascript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'hint',
				},
				{
					id: 'ms-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['typescript', 'javascript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'ms-iface-pascal-i',
					kind: 'interface',
					style: 'PascalCase',
					languages: ['typescript'],
					enabled: true,
					prefix: 'I',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'ms-enum-pascal',
					kind: 'enum',
					style: 'PascalCase',
					languages: ['typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'ms-type-pascal',
					kind: 'type',
					style: 'PascalCase',
					languages: ['typescript'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- PEP 8 (Python) -------------------------------------------------

	preset(
		'PEP 8 (Python)',
		'Python\'s PEP 8 style guide: 4-space indent, double quotes, 79-char limit, snake_case variables/functions, PascalCase classes, SCREAMING_SNAKE_CASE constants.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 79,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 4 },
			quotes: { 'python': 'double', '*': 'any' },
			semicolons: { '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { '*': 'any' },
			namingRules: [
				{
					id: 'pep8-var-snake',
					kind: 'variable',
					style: 'snake_case',
					languages: ['python'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'pep8-fn-snake',
					kind: 'function',
					style: 'snake_case',
					languages: ['python'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'pep8-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['python'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'pep8-const-screaming',
					kind: 'constant',
					style: 'SCREAMING_SNAKE_CASE',
					languages: ['python'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- Rust ------------------------------------------------------------

	preset(
		'Rust',
		'Idiomatic Rust: 4-space indent, LF endings, snake_case variables/functions/modules, PascalCase types/structs/enums, SCREAMING_SNAKE_CASE constants.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 100,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 4 },
			quotes: { '*': 'any' },
			semicolons: { '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { '*': 'same-line' },
			namingRules: [
				{
					id: 'rust-var-snake',
					kind: 'variable',
					style: 'snake_case',
					languages: ['rust'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'rust-fn-snake',
					kind: 'function',
					style: 'snake_case',
					languages: ['rust'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'rust-type-pascal',
					kind: 'type',
					style: 'PascalCase',
					languages: ['rust'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'rust-enum-pascal',
					kind: 'enum',
					style: 'PascalCase',
					languages: ['rust'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'rust-const-screaming',
					kind: 'constant',
					style: 'SCREAMING_SNAKE_CASE',
					languages: ['rust'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- Go --------------------------------------------------------------

	preset(
		'Go',
		'Idiomatic Go: tabs, LF, no semicolons, camelCase variables/functions, PascalCase exported types/functions.',
		{
			lineEnding: 'lf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'tabs', size: 4 },
			quotes: { 'go': 'double', '*': 'any' },
			semicolons: { '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { 'go': 'same-line', '*': 'any' },
			namingRules: [
				{
					id: 'go-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['go'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'go-fn-camel',
					kind: 'function',
					style: 'camelCase',
					languages: ['go'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'go-type-pascal',
					kind: 'type',
					style: 'PascalCase',
					languages: ['go'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- C# (Microsoft .NET conventions) --------------------------------

	preset(
		'C# (Microsoft)',
		'Microsoft .NET naming conventions: 4-space indent, CRLF, PascalCase classes/methods/properties/enums, camelCase parameters/variables, I-prefixed interfaces.',
		{
			lineEnding: 'crlf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 4 },
			quotes: { 'csharp': 'double', '*': 'any' },
			semicolons: { 'csharp': 'always', '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { 'csharp': 'next-line', '*': 'any' },
			namingRules: [
				{
					id: 'cs-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-iface-pascal-i',
					kind: 'interface',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: 'I',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-enum-pascal',
					kind: 'enum',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-fn-pascal',
					kind: 'function',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-prop-pascal',
					kind: 'property',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
				{
					id: 'cs-param-camel',
					kind: 'parameter',
					style: 'camelCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'warning',
				},
			],
		},
	),

	// ---- C# (StyleCop) --------------------------------------------------

	preset(
		'C# (StyleCop)',
		'StyleCop-compatible conventions: same rules as Microsoft .NET but with a 120-char line limit and warnings treated as errors.',
		{
			lineEnding: 'crlf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 120,
			enforceOnSave: false,
			defaultSeverity: 'error',
			indent: { style: 'spaces', size: 4 },
			quotes: { 'csharp': 'double', '*': 'any' },
			semicolons: { 'csharp': 'always', '*': 'any' },
			trailingCommas: { '*': 'any' },
			braceStyle: { 'csharp': 'next-line', '*': 'any' },
			namingRules: [
				{
					id: 'stylecop-class-pascal',
					kind: 'class',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-iface-pascal-i',
					kind: 'interface',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: 'I',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-enum-pascal',
					kind: 'enum',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-fn-pascal',
					kind: 'function',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-prop-pascal',
					kind: 'property',
					style: 'PascalCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-var-camel',
					kind: 'variable',
					style: 'camelCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
				{
					id: 'stylecop-param-camel',
					kind: 'parameter',
					style: 'camelCase',
					languages: ['csharp'],
					enabled: true,
					prefix: '',
					suffix: '',
					severity: 'error',
				},
			],
		},
	),

	// ---- CRLF (Windows) -------------------------------------------------

	preset(
		'Windows (CRLF)',
		'Enforce Windows-style CRLF line endings, 4-space indent, double quotes, always semicolons. Useful for legacy Windows projects.',
		{
			lineEnding: 'crlf',
			insertFinalNewline: true,
			trimTrailingWhitespace: true,
			maxLineLength: 0,
			enforceOnSave: false,
			defaultSeverity: 'warning',
			indent: { style: 'spaces', size: 4 },
			quotes: { '*': 'double' },
			semicolons: { '*': 'always' },
			trailingCommas: { '*': 'any' },
			braceStyle: { '*': 'same-line' },
			namingRules: [],
		},
	),

];
